fixed Android dotenv.gradle quotes matching
Fixed the regex - it caused syntax error in generated BuildConfig.java file when quotes were used in the `.env` file. `export VAR1="aa bb cc"` caused
```
/BuildConfig.java:15: error: unclosed string literal
  public static final String VAR1 = "aa bb cc"";
                                              ^
1 error
```